#!/usr/bin/env python

""" 
collate-genome-jenga-runs.py by Rohan Maddamsetti.

Input: the files in ../results/genome-jenga-runs.
Output: Three csv files generated by collating the genome jenga run files:
jenga_minimal_genome.csv
jenga_essential_genes.csv
jenga_essential_reactions.csv.

"""

from os.path import join, basename
from os import listdir


def sort_the_paths(pathlist):
    decorated_paths = []
    for path in pathlist:
        cur_rep = basename(path).split(".csv")[0].split("Rep")[-1]
        decorated_paths.append((cur_rep, path))
    decorated_paths.sort(key=lambda x: int(x[0]))
    sorted_paths = [x for (_, x) in decorated_paths]
    return sorted_paths


def collate_files(pathlist, outfilepath):
    sorted_pathlist = sort_the_paths(pathlist)
    header = None
    with open(outfilepath, "w") as out_fh:
        for path in sorted_pathlist:
            cur_rep = basename(path).split(".csv")[0].split("Rep")[-1]
            with open(path, "r") as in_fh:
                for i, line in enumerate(in_fh):
                    if i == 0 and header is None:
                        header = line.strip() + ",Replicate\n"
                        out_fh.write(header)
                    else:
                        outline = line.strip() + "," + cur_rep + "\n"
                        out_fh.write(outline)
    return
                    

def main():

    rdir = "../results/metabolic-enzymes"
    inputdir = join(rdir, "genome-jenga-runs")

    minimal_genome_files = [join(inputdir, x) for x in listdir(inputdir)
                            if "minimal_genome" in x]
    essential_genes_files = [join(inputdir, x) for x in listdir(inputdir)
                             if "essential_genes" in x]
    essential_reactions_files = [join(inputdir, x) for x in listdir(inputdir)
                                 if "essential_reactions" in x]
    collate_files(minimal_genome_files, join(rdir, "jenga_minimal_genome.csv"))
    collate_files(essential_genes_files, join(rdir, "jenga_essential_genes.csv"))
    collate_files(essential_reactions_files, join(rdir, "jenga_essential_reactions.csv"))
    return

main()


